"""aieasybatch — single-file build (generated by tools/build_single.py; do not edit).

Copy this one standard-library-only file into any project for zero-dependency batch
prompting. Regenerate from src/ after changes: python tools/build_single.py
"""
from __future__ import annotations

from abc import ABC, abstractmethod
from concurrent.futures import ThreadPoolExecutor, as_completed
from dataclasses import asdict, dataclass, field
from dataclasses import dataclass
from dataclasses import dataclass, field
from datetime import datetime, timezone
from pathlib import Path
import argparse
import hashlib
import json
import os
import random
import sys
import threading
import time
import urllib.error
import urllib.request
import uuid

__version__ = "0.1.0"

# ===== record.py =====
SCHEMA = "aieasybatch/v1"


def now_iso() -> str:
    return datetime.now(timezone.utc).isoformat()


def custom_id(provider: str, model: str, prompt: str,
              system: str | None = None, repeat: int = 0) -> str:
    """A stable, content-addressed cell identity.

    The same ``(provider, model, prompt, system, repeat)`` always hashes to the same
    id, so it does triple duty: the resume key for the live path, the ``custom_id``
    every provider batch API requires for out-of-order reassembly, and the merge/dedup
    key across parallel run files. Hex + length 32 keeps it inside the strictest
    provider rule (Anthropic: ``^[a-zA-Z0-9_-]{1,64}$``).
    """
    h = hashlib.sha256()
    h.update(provider.encode("utf-8")); h.update(b"\x00")
    h.update(model.encode("utf-8")); h.update(b"\x00")
    h.update((prompt or "").encode("utf-8")); h.update(b"\x00")
    h.update((system or "").encode("utf-8")); h.update(b"\x00")
    h.update(str(repeat).encode("utf-8"))
    return h.hexdigest()[:32]


@dataclass(frozen=True)
class Sampling:
    temperature: float = 1.0
    top_p: float = 1.0
    max_tokens: int = 512
    seed: int | None = 0
    reasoning_effort: str | None = None   # "minimal"|"low"|"medium"|"high" (reasoning models)


# Field order for the emitted JSON — purely cosmetic, but it makes the JSONL pleasant
# to read (identity first, the answer in the middle, bookkeeping last).
_ORDER = (
    "schema", "custom_id", "run_id", "ts",
    "provider", "model", "model_returned", "served_by",
    "prompt_id", "prompt", "system", "messages",
    "sampling", "repeat",
    "output", "finish_reason", "error",
    "usage", "cost_usd", "latency_ms",
    "prompt_meta", "model_meta", "raw",
)


@dataclass
class Record:
    # --- identity (required) ---
    custom_id: str
    run_id: str
    provider: str
    model: str
    prompt_id: str
    prompt: str
    sampling: Sampling
    # --- everything else has a default ---
    repeat: int = 0
    system: str | None = None
    messages: list | None = None          # set only for multi-turn; else prompt is canonical
    output: str | None = None             # raw text, unjudged; None on failure
    finish_reason: str | None = None
    error: dict | None = None             # None on success; {type, message, attempts} on failure
    model_returned: str | None = None     # what the API actually served
    served_by: str | None = None          # backend (e.g. OpenRouter route); auditable
    usage: dict | None = None             # normalized {input_tokens, output_tokens, total_tokens}
    cost_usd: float | None = None         # best-effort; None when the model isn't priced
    latency_ms: int | None = None
    prompt_meta: dict = field(default_factory=dict)
    model_meta: dict = field(default_factory=dict)
    raw: dict = field(default_factory=dict)
    schema: str = SCHEMA
    ts: str = field(default_factory=now_iso)

    @property
    def ok(self) -> bool:
        return self.error is None

    def to_dict(self) -> dict:
        d = asdict(self)                  # also converts the nested Sampling dataclass
        return {k: d[k] for k in _ORDER if k in d}

    def to_json(self) -> str:
        return json.dumps(self.to_dict(), ensure_ascii=False)

# ===== prompts.py =====
@dataclass
class Prompt:
    text: str
    id: str
    meta: dict = field(default_factory=dict)


def _read_text(source) -> str:
    if source == "-":
        return sys.stdin.read()
    return Path(source).read_text(encoding="utf-8")


def _coerce(row, i: int) -> Prompt:
    """Turn a raw row (str or dict) into a Prompt with a stable id."""
    if isinstance(row, Prompt):
        return row
    if isinstance(row, str):
        return Prompt(text=row, id=str(i))
    if isinstance(row, dict):
        text = row.get("text", row.get("prompt"))
        if text is None:
            raise ValueError(f"prompt object needs a 'text' (or 'prompt') field: {row!r}")
        return Prompt(text=str(text), id=str(row.get("id", i)), meta=dict(row.get("meta", {})))
    raise TypeError(f"unsupported prompt row: {row!r}")


def load_prompts(source) -> list[Prompt]:
    """Load prompts from a list, a file path, or stdin.

    - list ``[str | dict | Prompt]`` -> coerced directly
    - ``*.txt`` (or unknown extension) -> one non-blank line per prompt
    - ``*.jsonl`` -> one JSON value (string or object) per line
    - ``*.json``  -> a JSON array of strings or objects
    - ``"-"``     -> read stdin (treated as newline-delimited text)
    """
    if isinstance(source, (list, tuple)):
        return [_coerce(r, i) for i, r in enumerate(source)]

    name = str(source)
    text = _read_text(source)
    if name.endswith(".jsonl"):
        rows = [json.loads(line) for line in text.splitlines() if line.strip()]
    elif name.endswith(".json"):
        rows = json.loads(text)
        if isinstance(rows, dict):                 # tolerate {"prompts": [...]}
            rows = rows.get("prompts", rows)
    else:
        rows = [line for line in text.splitlines() if line.strip()]
    return [_coerce(r, i) for i, r in enumerate(rows)]

# ===== roster.py =====
_KNOWN = ("base_url", "key_env", "reasoning_effort", "max_tokens", "meta")


@dataclass
class ModelSpec:
    provider: str
    model: str
    base_url: str | None = None
    key_env: str | None = None
    reasoning_effort: str | None = None
    max_tokens: int | None = None       # per-model override of the run's max_tokens
    extra: dict = field(default_factory=dict)   # routing etc., passed to the adapter
    meta: dict = field(default_factory=dict)    # free-form -> model_meta in every record

    @property
    def label(self) -> str:
        return f"{self.provider}:{self.model}"


def parse_model(spec) -> ModelSpec:
    if isinstance(spec, ModelSpec):
        return spec
    if isinstance(spec, str):
        if ":" not in spec:
            raise ValueError(
                f"model selector must be 'provider:model_id' (e.g. 'openai:gpt-4o-mini'), got {spec!r}"
            )
        provider, model = spec.split(":", 1)        # split once: model ids may contain ':'
        return ModelSpec(provider=provider.strip(), model=model.strip())
    if isinstance(spec, dict):
        d = dict(spec)
        provider = d.pop("provider", None)
        model = d.pop("model", None) or d.pop("model_id", None)
        if not provider or not model:
            raise ValueError(f"model object needs 'provider' and 'model': {spec!r}")
        fields = {k: d.pop(k) for k in _KNOWN if k in d}
        extra = dict(fields.pop("extra", {})) if "extra" in fields else {}
        extra.update(d)                              # leftover keys (routing, ...) -> extra
        return ModelSpec(provider=provider, model=model, extra=extra, **fields)
    raise TypeError(f"unsupported model spec: {spec!r}")


def load_roster(source) -> list[ModelSpec]:
    """Load a roster from a list of selectors/dicts, or a JSON file.

    A roster file is ``{"models": [...]}`` or a bare ``[...]`` of selectors/dicts.
    """
    if isinstance(source, (list, tuple)):
        return [parse_model(s) for s in source]
    data = json.loads(Path(source).read_text(encoding="utf-8"))
    models = data["models"] if isinstance(data, dict) else data
    return [parse_model(m) for m in models]

# ===== usage.py =====
def normalize_usage(provider, raw):
    """Map a provider's raw usage dict onto ``{input,output,total}_tokens``."""
    if not raw:
        return None
    inp = raw.get("input_tokens", raw.get("prompt_tokens", raw.get("promptTokenCount")))
    out = raw.get("output_tokens", raw.get("completion_tokens", raw.get("candidatesTokenCount")))
    tot = raw.get("total_tokens", raw.get("totalTokenCount"))
    if tot is None and (inp is not None or out is not None):
        tot = (inp or 0) + (out or 0)
    if inp is None and out is None and tot is None:
        return None
    return {"input_tokens": inp, "output_tokens": out, "total_tokens": tot}


# USD per 1,000,000 tokens, (input, output). Best-effort and easy to override via
# run(prices=...). Order matters: list more specific keys first so the substring match
# prefers e.g. "gpt-4o-mini" over "gpt-4o".
DEFAULT_PRICES = {
    "gpt-4o-mini": (0.15, 0.60),
    "gpt-4.1-mini": (0.40, 1.60),
    "gpt-4.1": (2.00, 8.00),
    "gpt-4o": (2.50, 10.00),
    "gpt-5-mini": (0.25, 2.00),
    "gpt-5": (1.25, 10.00),
    "o4-mini": (1.10, 4.40),
    "claude-3-5-haiku": (0.80, 4.00),
    "claude-haiku-4": (1.00, 5.00),
    "claude-3-5-sonnet": (3.00, 15.00),
    "claude-sonnet-4": (3.00, 15.00),
    "claude-opus-4": (15.00, 75.00),
    "gemini-2.0-flash": (0.10, 0.40),
    "gemini-1.5-flash": (0.075, 0.30),
    "gemini-1.5-pro": (1.25, 5.00),
    "llama-3.1-8b": (0.05, 0.08),
    "llama-3.3-70b": (0.12, 0.30),
    "mistral-7b": (0.05, 0.10),
    "qwen-2.5-7b": (0.05, 0.10),
    "deepseek-chat": (0.27, 1.10),
}


def estimate_cost(model, usage, prices=None):
    """Best-effort USD cost for one call; ``None`` if the model isn't priced."""
    if not usage:
        return None
    table = dict(DEFAULT_PRICES)
    if prices:
        table.update(prices)
    ml = model.lower()
    match = next((k for k in table if k in ml), None)
    if match is None:
        return None
    price_in, price_out = table[match]
    inp = usage.get("input_tokens") or 0
    out = usage.get("output_tokens") or 0
    return round(inp / 1e6 * price_in + out / 1e6 * price_out, 8)

# ===== providers/base.py =====
class Provider(ABC):
    name: str

    @abstractmethod
    def chat(self, messages: list, sampling) -> tuple:
        """Return ``(output_text, meta)`` for a list of chat messages."""
        raise NotImplementedError

    def generate(self, prompt: str, sampling, system: str | None = None) -> tuple:
        messages = []
        if system:
            messages.append({"role": "system", "content": system})
        messages.append({"role": "user", "content": prompt})
        return self.chat(messages, sampling)

# ===== providers/http.py =====
# Connect directly, bypassing any ambient HTTPS_PROXY (see note 1 above).
_OPENER = urllib.request.build_opener(urllib.request.ProxyHandler({}))


class HttpError(RuntimeError):
    def __init__(self, message, *, code=None, transient=False, attempts=None):
        super().__init__(message)
        self.code = code
        self.transient = transient
        self.attempts = attempts


def request_json(url, *, headers=None, body=None, method="POST",
                 timeout=60.0, max_retries=4):
    """Send a JSON request and return the parsed JSON response.

    ``body`` is JSON-encoded when present (for GET, pass ``body=None``). Raises
    ``HttpError`` on failure, after exhausting retries for transient errors.
    """
    data = json.dumps(body).encode("utf-8") if body is not None else None
    hdrs = dict(headers or {})
    if data is not None:
        hdrs.setdefault("Content-Type", "application/json")

    delay, last = 2.0, None
    for attempt in range(max_retries):
        try:
            req = urllib.request.Request(url, data=data, headers=hdrs, method=method)
            with _OPENER.open(req, timeout=timeout) as resp:
                raw = resp.read().decode("utf-8")
                return json.loads(raw) if raw else {}
        except urllib.error.HTTPError as e:
            code = e.code
            transient = (code == 429 or 500 <= code < 600)
            try:
                detail = e.read().decode("utf-8", "replace")[:600]
            except Exception:
                detail = ""
            last = HttpError(f"HTTP {code}: {detail}", code=code,
                             transient=transient, attempts=attempt + 1)
            if not transient:
                raise last                          # permanent — give up now
        except (urllib.error.URLError, TimeoutError) as e:
            last = HttpError(f"network error: {e}", transient=True, attempts=attempt + 1)
        if attempt == max_retries - 1:
            break
        time.sleep(delay)
        delay *= 2
    raise last


def get_json(url, *, headers=None, timeout=60.0, max_retries=4):
    return request_json(url, headers=headers, body=None, method="GET",
                        timeout=timeout, max_retries=max_retries)

# ===== providers/mock.py =====
_BITS = [
    "Here is a concise take:",
    "Consider it from three angles.",
    "The short answer is yes, with caveats.",
    "A small worked example follows.",
    "In one line: it depends on the context.",
    "Two things matter most here.",
]


class MockProvider(Provider):
    name = "mock"

    def __init__(self, model: str = "mock", **_):
        self.model = model

    def chat(self, messages, sampling):
        prompt = next((m["content"] for m in reversed(messages)
                       if m.get("role") == "user"), "")
        key = f"{self.model}|{prompt}|{len(messages)}|{sampling.seed}".encode("utf-8")
        rng = random.Random(hashlib.sha256(key).hexdigest())
        body = " ".join(rng.choice(_BITS) for _ in range(rng.randint(1, 3)))
        text = f"[{self.model}] {body}"
        usage = {"prompt_tokens": max(1, len(prompt) // 4),
                 "completion_tokens": max(1, len(text) // 4)}
        meta = {"usage": usage, "served_by": "mock", "model_returned": self.model,
                "finish_reason": "stop", "synthetic": True}
        return text, meta

# ===== providers/openai_compat.py =====
# Bare model names (after any vendor prefix) that use the reasoning interface.
_REASONING_PREFIXES = ("gpt-5", "o1", "o3", "o4")


class OpenAICompatProvider(Provider):
    name = "openai_compat"

    def __init__(self, model, *, base_url, key_env=None, reasoning_effort=None,
                 routing=None, extra_headers=None, provider_name=None,
                 timeout=90.0, max_retries=4, api_key=None):
        self.model = model
        self.base_url = base_url.rstrip("/")
        self.endpoint = self.base_url + "/chat/completions"
        self.key_env = key_env
        self.reasoning_effort = reasoning_effort
        self.routing = routing                       # OpenRouter provider-routing block
        self.extra_headers = dict(extra_headers or {})
        self.provider_name = provider_name or "openai_compat"
        self.timeout = timeout
        self.max_retries = max_retries
        self.api_key = api_key or (os.environ.get(key_env) if key_env else None)
        if key_env and not self.api_key:
            raise ValueError(f"set {key_env} to use provider {self.provider_name!r} (model {model!r})")

    def _is_reasoning(self):
        tail = self.model.lower().split("/")[-1]      # tolerate vendor-prefixed slugs
        return tail.startswith(_REASONING_PREFIXES)

    def _payload(self, messages, sampling):
        body = {"model": self.model, "messages": messages}
        if self._is_reasoning():
            body["max_completion_tokens"] = sampling.max_tokens
            if self.reasoning_effort:
                body["reasoning_effort"] = self.reasoning_effort
            # temperature + top_p omitted: reasoning models only accept the defaults
        else:
            body["temperature"] = sampling.temperature
            body["max_tokens"] = sampling.max_tokens
            if sampling.top_p != 1.0:
                body["top_p"] = sampling.top_p
        if sampling.seed is not None:
            body["seed"] = sampling.seed
        if self.routing:
            body["provider"] = self.routing
        return body

    def chat(self, messages, sampling):
        headers = {"Content-Type": "application/json"}
        if self.api_key:
            headers["Authorization"] = f"Bearer {self.api_key}"
        headers.update(self.extra_headers)
        body = request_json(self.endpoint, headers=headers,
                            body=self._payload(messages, sampling),
                            timeout=self.timeout, max_retries=self.max_retries)
        if "choices" not in body:                     # some backends return errors as HTTP 200
            err = body.get("error")
            msg = (err.get("message") if isinstance(err, dict) else err) or str(body)[:300]
            raise HttpError(f"no choices in response: {msg}", transient=False)
        choice = (body.get("choices") or [{}])[0]
        text = (choice.get("message") or {}).get("content") or ""
        finish = choice.get("finish_reason")
        meta = {
            "usage": body.get("usage"),
            "served_by": body.get("provider") or self.provider_name,
            "model_returned": body.get("model"),
            "response_id": body.get("id"),
            "finish_reason": finish,
            "reasoning_effort": self.reasoning_effort,
        }
        if not text and self._is_reasoning() and finish in ("length", None):
            meta["empty_reason"] = "reasoning_starved"
        return text, meta

# ===== providers/anthropic.py =====
_VERSION = "2023-06-01"


class AnthropicProvider(Provider):
    name = "anthropic"

    def __init__(self, model, *, base_url=None, key_env=None,
                 timeout=90.0, max_retries=4, api_key=None):
        self.model = model.split("/", 1)[1] if model.startswith("anthropic/") else model
        self.base_url = (base_url or "https://api.anthropic.com/v1").rstrip("/")
        self.endpoint = self.base_url + "/messages"
        self.key_env = key_env or "ANTHROPIC_API_KEY"
        self.timeout = timeout
        self.max_retries = max_retries
        self.api_key = api_key or os.environ.get(self.key_env)
        if not self.api_key:
            raise ValueError(f"set {self.key_env} to use the anthropic provider (model {model!r})")

    def _payload(self, messages, sampling):
        system = " ".join(m["content"] for m in messages if m["role"] == "system")
        convo = [{"role": m["role"], "content": m["content"]}
                 for m in messages if m["role"] != "system"]
        body = {"model": self.model, "max_tokens": sampling.max_tokens,
                "temperature": sampling.temperature, "messages": convo}
        if system:
            body["system"] = system
        if sampling.top_p != 1.0:
            body["top_p"] = sampling.top_p
        return body

    def chat(self, messages, sampling):
        headers = {"x-api-key": self.api_key, "anthropic-version": _VERSION,
                   "Content-Type": "application/json"}
        body = request_json(self.endpoint, headers=headers,
                            body=self._payload(messages, sampling),
                            timeout=self.timeout, max_retries=self.max_retries)
        if "content" not in body:
            err = body.get("error")
            msg = (err.get("message") if isinstance(err, dict) else err) or str(body)[:300]
            raise HttpError(f"no content in response: {msg}", transient=False)
        text = "".join(b.get("text", "") for b in body.get("content", [])
                       if b.get("type") == "text")
        usage = body.get("usage") or {}
        meta = {
            "usage": {"input_tokens": usage.get("input_tokens"),
                      "output_tokens": usage.get("output_tokens")},
            "served_by": "anthropic",
            "model_returned": body.get("model"),
            "response_id": body.get("id"),
            "finish_reason": body.get("stop_reason"),
        }
        return text, meta

# ===== providers/gemini.py =====
class GeminiProvider(Provider):
    name = "gemini"

    def __init__(self, model, *, base_url=None, key_env=None,
                 timeout=90.0, max_retries=4, api_key=None):
        self.model = model.split("/", 1)[1] if model.startswith("models/") else model
        self.base_url = (base_url or "https://generativelanguage.googleapis.com/v1beta").rstrip("/")
        self.key_env = key_env or "GEMINI_API_KEY"
        self.timeout = timeout
        self.max_retries = max_retries
        self.api_key = (api_key or os.environ.get(self.key_env)
                        or os.environ.get("GOOGLE_API_KEY"))
        if not self.api_key:
            raise ValueError(f"set {self.key_env} to use the gemini provider (model {model!r})")

    def _payload(self, messages, sampling):
        contents, system = [], []
        for m in messages:
            if m["role"] == "system":
                system.append(m["content"])
                continue
            role = "model" if m["role"] == "assistant" else "user"
            contents.append({"role": role, "parts": [{"text": m["content"]}]})
        cfg = {"temperature": sampling.temperature, "maxOutputTokens": sampling.max_tokens}
        if sampling.top_p != 1.0:
            cfg["topP"] = sampling.top_p
        body = {"contents": contents, "generationConfig": cfg}
        if system:
            body["systemInstruction"] = {"parts": [{"text": " ".join(system)}]}
        return body

    def chat(self, messages, sampling):
        url = f"{self.base_url}/models/{self.model}:generateContent"
        headers = {"x-goog-api-key": self.api_key, "Content-Type": "application/json"}
        body = request_json(url, headers=headers, body=self._payload(messages, sampling),
                            timeout=self.timeout, max_retries=self.max_retries)
        cands = body.get("candidates")
        if not cands:
            err = body.get("error")
            msg = (err.get("message") if isinstance(err, dict) else err) or str(body)[:300]
            raise HttpError(f"no candidates in response: {msg}", transient=False)
        parts = (cands[0].get("content") or {}).get("parts") or []
        text = "".join(p.get("text", "") for p in parts if "text" in p)
        um = body.get("usageMetadata") or {}
        meta = {
            "usage": {"promptTokenCount": um.get("promptTokenCount"),
                      "candidatesTokenCount": um.get("candidatesTokenCount"),
                      "totalTokenCount": um.get("totalTokenCount")},
            "served_by": "gemini",
            "model_returned": body.get("modelVersion") or self.model,
            "response_id": body.get("responseId"),
            "finish_reason": cands[0].get("finishReason"),
        }
        return text, meta

# ===== registry.py =====
# name -> (base_url, key_env, options). key_env=None means "no key needed" (local).
_OPENAI_COMPAT = {
    "openai":     ("https://api.openai.com/v1",            "OPENAI_API_KEY",     {}),
    "openrouter": ("https://openrouter.ai/api/v1",         "OPENROUTER_API_KEY",
                   {"headers": {"HTTP-Referer": "https://github.com/liam499/easy-batch-prompting",
                                "X-Title": "aieasybatch"}, "supports_routing": True}),
    "groq":       ("https://api.groq.com/openai/v1",       "GROQ_API_KEY",       {}),
    "together":   ("https://api.together.xyz/v1",          "TOGETHER_API_KEY",   {}),
    "fireworks":  ("https://api.fireworks.ai/inference/v1", "FIREWORKS_API_KEY", {}),
    "deepinfra":  ("https://api.deepinfra.com/v1/openai",  "DEEPINFRA_API_KEY",  {}),
    "deepseek":   ("https://api.deepseek.com",             "DEEPSEEK_API_KEY",   {}),
    "xai":        ("https://api.x.ai/v1",                  "XAI_API_KEY",        {}),
    "mistral":    ("https://api.mistral.ai/v1",            "MISTRAL_API_KEY",    {}),
    "ollama":     ("http://localhost:11434/v1",            None,                 {}),
    "lmstudio":   ("http://localhost:1234/v1",             None,                 {}),
    "vllm":       ("http://localhost:8000/v1",             None,                 {}),
}

_REGISTRY = {}   # custom name -> factory(spec) -> Provider


def register(name, factory):
    """Register a custom provider: ``factory`` takes a ``ModelSpec``, returns a ``Provider``."""
    _REGISTRY[name] = factory


def known_providers():
    return sorted(set(_OPENAI_COMPAT) | {"anthropic", "gemini", "mock"} | set(_REGISTRY))


def get_provider(spec):
    name = spec.provider
    if name in _REGISTRY:
        return _REGISTRY[name](spec)
    if name == "mock":
        return MockProvider(model=spec.model)
    if name in _OPENAI_COMPAT:
        return _make_openai_compat(name, spec)
    if name == "anthropic":
        return AnthropicProvider(model=spec.model, base_url=spec.base_url, key_env=spec.key_env)
    if name == "gemini":
        return GeminiProvider(model=spec.model, base_url=spec.base_url, key_env=spec.key_env)
    raise ValueError(
        f"unknown provider {name!r}. Known: {', '.join(known_providers())}. "
        f"Add one with aieasybatch.register({name!r}, factory)."
    )


def _make_openai_compat(name, spec):
    base_url, key_env, opts = _OPENAI_COMPAT[name]
    routing = spec.extra.get("routing") if opts.get("supports_routing") else None
    return OpenAICompatProvider(
        model=spec.model,
        base_url=spec.base_url or base_url,
        key_env=spec.key_env or key_env,
        reasoning_effort=spec.reasoning_effort,
        routing=routing,
        extra_headers=opts.get("headers"),
        provider_name=name,
    )

# ===== core.py =====
@dataclass
class RunResult:
    path: str | None
    ok: int
    failed: int
    run_id: str
    _records: list | None = None

    def records(self):
        """Yield the run's records as dicts (from memory if ``out=""``, else re-read the file)."""
        if self._records is not None:
            yield from self._records
        elif self.path:
            for line in Path(self.path).read_text(encoding="utf-8").splitlines():
                if line.strip():
                    yield json.loads(line)


def _err_type(exc) -> str:
    transient = getattr(exc, "transient", None)
    if transient is True:
        return "transient"
    return "permanent"


def _completed_ids(path, retry_errors):
    """custom_ids already finished in ``path`` (success, or permanent error if not retrying)."""
    done = set()
    for line in Path(path).read_text(encoding="utf-8").splitlines():
        if not line.strip():
            continue
        try:
            rec = json.loads(line)
        except Exception:
            continue
        cid = rec.get("custom_id")
        if not cid:
            continue
        err = rec.get("error")
        if err is None:
            done.add(cid)
        elif not retry_errors and err.get("type") == "permanent":
            done.add(cid)
    return done


def _open_sink(out, resume):
    """Return (path_or_None, write_fn_or_None, close_fn_or_None, in_memory_bool)."""
    if out == "-":
        return None, (lambda line: sys.stdout.write(line + "\n")), None, False
    if out == "" or out is None:
        return None, None, None, True
    path = str(out)
    fh = open(path, "a" if resume else "w", encoding="utf-8")

    def write(line):
        fh.write(line + "\n")
        fh.flush()

    return path, write, fh.close, False


def run(prompts, models, out="run.jsonl", *,
        repeats=1, temperature=1.0, top_p=1.0, max_tokens=512, seed=0,
        concurrency=16, per_model_concurrency=None,
        resume=False, retry_errors=False,
        system=None, on_record=None, registry=None, prices=None,
        timeout=60.0, max_retries=4):
    """Fan a list of prompts across a roster of models and collect every answer.

    Parameters mirror the CLI. ``prompts`` and ``models`` accept lists, file paths, or
    ``"-"`` (stdin) — see ``load_prompts`` / ``load_roster``. ``out`` is a file path,
    ``"-"`` for stdout, or ``""`` to keep records in memory (``RunResult.records()``).
    Returns a ``RunResult`` (``path, ok, failed, run_id``).
    """
    prompt_list = load_prompts(prompts)
    roster = load_roster(models)
    run_id = uuid.uuid4().hex[:12]

    # One provider per distinct model, built once and reused. A build failure (e.g. a
    # missing API key) skips that whole model with a clear message rather than emitting
    # an error record per cell — it's a config problem, not a per-call one.
    providers, sems = {}, {}
    for spec in roster:
        if spec.label in providers:
            continue
        try:
            providers[spec.label] = (registry.get(spec) if registry is not None
                                     else get_provider(spec))
        except Exception as exc:
            print(f"[skip] {spec.label}: {exc}", file=sys.stderr)
            providers[spec.label] = None
        if per_model_concurrency:
            sems[spec.label] = threading.BoundedSemaphore(per_model_concurrency)

    done = (_completed_ids(out, retry_errors)
            if resume and isinstance(out, str) and out not in ("", "-") and Path(out).exists()
            else set())

    # Build the grid: model × prompt × repeat, skipping cells already done.
    tasks = []
    for spec in roster:
        if providers.get(spec.label) is None:
            continue
        spec_max = spec.max_tokens or max_tokens
        for p in prompt_list:
            for r in range(repeats):
                cid = custom_id(spec.provider, spec.model, p.text, system, r)
                if cid in done:
                    continue
                sampling = Sampling(temperature=temperature, top_p=top_p, max_tokens=spec_max,
                                    seed=(None if seed is None else seed + r),
                                    reasoning_effort=spec.reasoning_effort)
                tasks.append((spec, p, r, cid, sampling))

    # Shuffle so models/providers interleave instead of running block-by-block — spreads
    # provider load and gives early cross-model coverage. Seeded for reproducibility.
    random.Random(seed or 0).shuffle(tasks)

    path, write, close, in_memory = _open_sink(out, resume)
    collected = [] if in_memory else None
    ok = failed = 0
    lock = threading.Lock()

    def work(task):
        spec, p, r, cid, sampling = task
        provider = providers[spec.label]
        sem = sems.get(spec.label)
        rec = Record(custom_id=cid, run_id=run_id, provider=spec.provider, model=spec.model,
                     prompt_id=p.id, prompt=p.text, system=system, sampling=sampling,
                     repeat=r, prompt_meta=p.meta, model_meta=spec.meta)
        t0 = time.monotonic()
        try:
            messages = []
            if system:
                messages.append({"role": "system", "content": system})
            messages.append({"role": "user", "content": p.text})
            if sem:
                sem.acquire()
            try:
                text, meta = provider.chat(messages, sampling)
            finally:
                if sem:
                    sem.release()
            meta = meta or {}
            rec.output = text
            rec.finish_reason = meta.get("finish_reason")
            rec.model_returned = meta.get("model_returned")
            rec.served_by = meta.get("served_by")
            rec.usage = normalize_usage(spec.provider, meta.get("usage"))
            rec.cost_usd = estimate_cost(spec.model, rec.usage, prices)
            for k in ("empty_reason", "response_id", "reasoning_effort"):
                if k in meta and meta[k] is not None:
                    rec.raw[k] = meta[k]
            success = True
        except Exception as exc:
            rec.error = {"type": _err_type(exc), "message": str(exc)[:600],
                         "attempts": getattr(exc, "attempts", None)}
            success = False
        rec.latency_ms = int((time.monotonic() - t0) * 1000)
        return rec, success

    with ThreadPoolExecutor(max_workers=concurrency) as pool:
        futures = [pool.submit(work, t) for t in tasks]
        for fut in as_completed(futures):
            rec, success = fut.result()
            line = rec.to_json()
            with lock:
                if write:
                    write(line)
                if collected is not None:
                    collected.append(json.loads(line))
                if success:
                    ok += 1
                else:
                    failed += 1
            if on_record:
                try:
                    on_record(rec)
                except Exception:
                    pass

    if close:
        close()
    return RunResult(path=path, ok=ok, failed=failed, run_id=run_id, _records=collected)

# ===== cli.py =====
def _add_run(sub):
    p = sub.add_parser("run", help="fan prompts across a roster of models (live calls)")
    p.add_argument("prompts", nargs="?", help="prompts file, or '-' for stdin")
    p.add_argument("-p", "--prompt", action="append", metavar="TEXT",
                   help="an inline prompt (repeatable)")
    p.add_argument("-m", "--model", action="append", metavar="PROVIDER:ID",
                   help="a model selector like openai:gpt-4o-mini (repeatable)")
    p.add_argument("--roster", metavar="FILE", help="a roster JSON file of models")
    p.add_argument("-o", "--out", default="-", metavar="FILE",
                   help="output JSONL path, or '-' for stdout (default)")
    p.add_argument("--system", metavar="TEXT", help="system prompt applied to every call")
    p.add_argument("--repeats", type=int, default=1)
    p.add_argument("--temperature", type=float, default=1.0)
    p.add_argument("--top-p", type=float, default=1.0, dest="top_p")
    p.add_argument("--max-tokens", type=int, default=512, dest="max_tokens")
    p.add_argument("--seed", type=int, default=0)
    p.add_argument("--concurrency", type=int, default=16, help="total in-flight calls")
    p.add_argument("--per-model", type=int, default=None, dest="per_model",
                   help="max simultaneous calls to any one model (the 429 guard)")
    p.add_argument("--resume", action="store_true",
                   help="skip cells already complete in --out; fill only the gaps")
    p.add_argument("--retry-errors", action="store_true", dest="retry_errors",
                   help="on resume, also retry cells that previously errored")
    p.add_argument("-q", "--quiet", action="store_true", help="don't print the summary")
    p.set_defaults(func=_cmd_run)


def _cmd_run(args) -> int:
    # prompts: inline -p wins, else positional path/stdin
    if args.prompt:
        prompts = list(args.prompt)
    elif args.prompts:
        prompts = args.prompts
    else:
        print("error: provide prompts (a file, '-', or one or more -p)", file=sys.stderr)
        return 2

    # models: combine -m selectors and a --roster file
    models = list(args.model or [])
    if args.roster:
        models += load_roster(args.roster)
    if not models:
        print("error: provide at least one -m provider:model or a --roster file", file=sys.stderr)
        return 2

    if args.resume and args.out in ("-", ""):
        print("error: --resume needs a file --out (not stdout)", file=sys.stderr)
        return 2

    result = run(
        prompts, models, out=args.out,
        repeats=args.repeats, temperature=args.temperature, top_p=args.top_p,
        max_tokens=args.max_tokens, seed=args.seed,
        concurrency=args.concurrency, per_model_concurrency=args.per_model,
        resume=args.resume, retry_errors=args.retry_errors, system=args.system,
    )
    if not args.quiet:
        where = result.path or "stdout"
        print(f"wrote {result.ok + result.failed} records "
              f"({result.ok} ok, {result.failed} failed) to {where}", file=sys.stderr)
    return 0


def build_parser() -> argparse.ArgumentParser:
    ap = argparse.ArgumentParser(
        prog="aieasybatch",
        description="Brain-dead-simple batch prompting: prompts × a roster of models "
                    "-> one JSONL with every answer. Zero dependencies.",
    )
    ap.add_argument("--version", action="version", version=f"aieasybatch {__version__}")
    sub = ap.add_subparsers(dest="cmd")
    _add_run(sub)
    _maybe_add_optional(sub)
    return ap


def _maybe_add_optional(sub):
    """Register the view/batch verbs if their modules are present (added in later phases)."""
    try:
        add_view(sub)
    except Exception:
        pass
    try:
        add_batch(sub)
    except Exception:
        pass


def main(argv=None) -> int:
    ap = build_parser()
    args = ap.parse_args(argv)
    if not getattr(args, "func", None):
        ap.print_help(sys.stderr)
        return 1
    return args.func(args)

if __name__ == "__main__":
    import sys as _sys
    _sys.exit(main())
