"""Provider locking — reproducibility for OpenRouter rosters.

OpenRouter load-balances a model slug across many backends at different quantizations.
For a reproducible run, pin each model to one backend (one set of weights) with
fallbacks off. ``lock`` resolves each model's endpoints and picks the model's own vendor
at the highest precision with the best recent uptime, then writes a roster with
``extra.routing`` pinned and the chosen provider/quant recorded (auditable afterwards via
each record's ``served_by``).

    aieasybatch lock --roster roster.json --out roster.locked.json   # no key needed
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

from .providers.http import get_json
from .roster import load_roster

# Higher = preferred. First-party endpoints report "unknown" precision and are
# trustworthy, so they rank just under explicit high precision.
_PRECISION_RANK = {"fp32": 7, "bf16": 6, "fp16": 6, "unknown": 5, None: 4,
                   "fp8": 3, "int8": 3, "fp4": 1, "int4": 1}


def _endpoints(slug):
    url = f"https://openrouter.ai/api/v1/models/{slug}/endpoints"
    return get_json(url, timeout=30)["data"]["endpoints"]


def pick_endpoint(slug, endpoints):
    """Pick the model's own vendor first, then precision, then recent uptime."""
    if not endpoints:
        return None
    author = slug.split("/")[0].lower()

    def author_match(e):
        prov = (e.get("tag") or "").split("/")[0].lower()
        return 1 if (author and (author in prov or prov in author)) else 0

    return max(endpoints, key=lambda e: (author_match(e),
                                         _PRECISION_RANK.get(e.get("quantization"), 4),
                                         e.get("uptime_last_30m") or 0.0))


def _spec_dict(s):
    d = {"provider": s.provider, "model": s.model}
    for k in ("base_url", "key_env", "reasoning_effort", "max_tokens"):
        v = getattr(s, k)
        if v:
            d[k] = v
    if s.meta:
        d["meta"] = s.meta
    if s.extra:
        d["extra"] = dict(s.extra)
    return d


def lock_roster(roster_source, out_path="roster.locked.json"):
    locked = []
    for s in load_roster(roster_source):
        if s.provider != "openrouter":
            locked.append(_spec_dict(s))           # only OpenRouter slugs route this way
            continue
        try:
            eps = _endpoints(s.model)
        except Exception as exc:
            print(f"[drop] {s.model}: {exc}", file=sys.stderr)
            continue
        ep = pick_endpoint(s.model, eps)
        if not ep:
            print(f"[drop] {s.model}: no endpoints", file=sys.stderr)
            continue
        prov_slug = (ep.get("tag") or "").split("/")[0] or ep.get("provider_name")
        d = _spec_dict(s)
        d.setdefault("extra", {})
        d["extra"]["routing"] = {"order": [prov_slug], "allow_fallbacks": False}
        d["extra"]["locked_provider"] = ep.get("provider_name")
        d["extra"]["locked_quantization"] = ep.get("quantization")
        locked.append(d)
        print(f"[lock] {s.model:44} -> {ep.get('provider_name')} ({ep.get('quantization')})",
              file=sys.stderr)
    Path(out_path).write_text(json.dumps(
        {"_comment": "Auto-generated by `aieasybatch lock`. Providers pinned, fallbacks off.",
         "models": locked}, indent=2, ensure_ascii=False), encoding="utf-8")
    print(f"wrote {out_path} ({len(locked)} models)", file=sys.stderr)
    return out_path


def add_cli(sub):
    p = sub.add_parser("lock", help="pin OpenRouter models to one backend/quant for reproducibility")
    p.add_argument("--roster", required=True, help="roster JSON to lock")
    p.add_argument("--out", default="roster.locked.json")
    p.set_defaults(func=lambda a: (lock_roster(a.roster, a.out), 0)[1])
