#!/usr/bin/env python3
"""Amalgamate the ``aieasybatch`` package into one vendorable file: ``aieasybatch.py``.

The package under ``src/aieasybatch`` is the source of truth; this script produces a
single standard-library-only file you can copy into any project (no ``pip install``).
It stays a ~100-line concatenator — not a bundler — precisely because the core imports
stdlib + siblings only (enforced by ``tests/test_no_third_party_imports.py``):

    topological concat  +  strip sibling/`__future__` imports  +  hoist stdlib imports

The view/batch verbs and the JS port are intentionally *not* amalgamated; the single
file is the live core (run) plus the four providers — the "drops in anywhere" subset.
"""
from __future__ import annotations

import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
PKG = ROOT / "src" / "aieasybatch"
OUT = ROOT / "aieasybatch.py"

# Dependency order. Only files that exist are included, so this same script works
# before the live providers land (Phase 3) and after.
MODULES = [
    "record.py", "prompts.py", "roster.py", "usage.py",
    "providers/base.py", "providers/http.py", "providers/mock.py",
    "providers/openai_compat.py", "providers/anthropic.py", "providers/gemini.py",
    "registry.py", "core.py", "cli.py",
]

_REL_IMPORT = re.compile(r"^\s*from\s+\.+")                       # from . / from .. (any indent)
_FUTURE = re.compile(r"^\s*from\s+__future__\s+import\b")
_TOP_IMPORT = re.compile(r"^(import\s+\S|from\s+[A-Za-z_]\S*\s+import\b)")  # column-0 stdlib import


def _version() -> str:
    m = re.search(r'__version__\s*=\s*"([^"]+)"', (PKG / "__init__.py").read_text())
    return m.group(1) if m else "0.0.0"


def _strip_leading_docstring(lines):
    i = 0
    while i < len(lines) and (not lines[i].strip() or lines[i].lstrip().startswith("#")):
        i += 1
    if i < len(lines) and re.match(r'\s*[rbu]?("""|\'\'\')', lines[i]):
        quote = '"""' if '"""' in lines[i] else "'''"
        if lines[i].count(quote) >= 2:                # one-line docstring
            return lines[:i] + lines[i + 1:]
        j = i + 1
        while j < len(lines) and quote not in lines[j]:
            j += 1
        return lines[:i] + lines[j + 1:]
    return lines


def build(write: bool = True) -> str:
    stdlib_imports = set()
    bodies = []
    for rel in MODULES:
        path = PKG / rel
        if not path.exists():
            continue
        lines = _strip_leading_docstring(path.read_text(encoding="utf-8").splitlines())
        kept = []
        for ln in lines:
            if _FUTURE.match(ln) or _REL_IMPORT.match(ln):
                continue                              # siblings become module globals
            if _TOP_IMPORT.match(ln):
                stdlib_imports.add(ln.strip())        # hoist to the top, deduped
                continue
            kept.append(ln)
        bodies.append(f"# ===== {rel} =====\n" + "\n".join(kept).strip("\n") + "\n")

    parts = [
        '"""aieasybatch — single-file build (generated by tools/build_single.py; do not edit).\n\n'
        "Copy this one standard-library-only file into any project for zero-dependency batch\n"
        'prompting. Regenerate from src/ after changes: python tools/build_single.py\n"""',
        "from __future__ import annotations",
        "",
        *sorted(stdlib_imports),
        "",
        f'__version__ = "{_version()}"',
        "",
        *bodies,
        'if __name__ == "__main__":',
        "    import sys as _sys",
        "    _sys.exit(main())",
        "",
    ]
    text = "\n".join(parts)
    if write:
        OUT.write_text(text, encoding="utf-8")
    return text


if __name__ == "__main__":
    build(write=True)
    print(f"wrote {OUT} ({OUT.stat().st_size} bytes)")
